sonar.organization=telepat-io
sonar.projectKey=telepat-io_ideon
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=src/**/__tests__/**,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/cli/**,src/bin/**
