import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  writingGuideSidebar: [
    {
      type: 'category',
      label: 'General Advice',
      link: {
        type: 'generated-index',
        title: 'General Advice',
      },
      items: [{type: 'autogenerated', dirName: 'general'}],
    },
    {
      type: 'category',
      label: 'By Intent',
      link: {
        type: 'generated-index',
        title: 'By Intent',
      },
      items: [{type: 'autogenerated', dirName: 'content-intent'}],
    },
    {
      type: 'category',
      label: 'By Format',
      link: {
        type: 'generated-index',
        title: 'By Format',
      },
      items: [{type: 'autogenerated', dirName: 'formats'}],
    },
    {
      type: 'category',
      label: 'By Style',
      link: {
        type: 'generated-index',
        title: 'By Style',
      },
      items: [{type: 'autogenerated', dirName: 'styles'}],
    },
    {
      type: 'category',
      label: 'References',
      link: {
        type: 'generated-index',
        title: 'References',
      },
      items: [{type: 'autogenerated', dirName: 'references'}],
    },
  ],
};

export default sidebars;
